const $=id=>document.getElementById(id),src=$('sourceCanvas'),out=$('resultCanvas'),box=$('sourceBox');let img=null,pts=[],mode='original',drag=-1,fullCanvas=document.createElement('canvas');
async function openFile(f){if(!f)return;$('error').textContent='Opening photo…';try{img=await createImageBitmap(f);fullCanvas.width=img.width;fullCanvas.height=img.height;fullCanvas.getContext('2d').drawImage(img,0,0);const available=Math.max(260,Math.min(720,document.documentElement.clientWidth-32)),s=Math.min(1,available/img.width);src.width=Math.round(img.width*s);src.height=Math.round(img.height*s);src.getContext('2d').drawImage(img,0,0,src.width,src.height);reset();$('editor').hidden=false;$('error').textContent='';requestAnimationFrame(update)}catch(e){$('error').textContent='This image could not be opened. Try JPG, PNG or WebP.'}}
$('libraryFile').addEventListener('change',e=>openFile(e.target.files[0]));
function reset(){const m=.07;pts=[[m,m],[1-m,m],[1-m,1-m],[m,1-m]]}
function handles(){const r=src.getBoundingClientRect(),br=box.getBoundingClientRect(),w=r.width,h=r.height,ox=r.left-br.left,oy=r.top-br.top;document.querySelectorAll('.corner').forEach((el,i)=>{el.style.left=`${ox+pts[i][0]*w}px`;el.style.top=`${oy+pts[i][1]*h}px`})}
function dist(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1])}
function solve(A,b){for(let i=0;i<8;i++){let p=i;for(let j=i+1;j<8;j++)if(Math.abs(A[j][i])>Math.abs(A[p][i]))p=j;[A[i],A[p]]=[A[p],A[i]];[b[i],b[p]]=[b[p],b[i]];let d=A[i][i]||1e-12;for(let k=i;k<8;k++)A[i][k]/=d;b[i]/=d;for(let j=0;j<8;j++)if(j!==i){let f=A[j][i];for(let k=i;k<8;k++)A[j][k]-=f*A[i][k];b[j]-=f*b[i]}}return b}
function homography(dst,source){let A=[],b=[];for(let i=0;i<4;i++){let[x,y]=dst[i],[u,v]=source[i];A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v)}let h=solve(A,b);return [...h,1]}
function render(){if(!img)return;const p=pts.map(([x,y])=>[x*img.width,y*img.height]),w=Math.max(1,Math.round(Math.max(dist(p[0],p[1]),dist(p[3],p[2])))),h=Math.max(1,Math.round(Math.max(dist(p[0],p[3]),dist(p[1],p[2])))),max=1800,ss=Math.min(1,max/Math.max(w,h)),W=Math.max(1,Math.round(w*ss)),H=Math.max(1,Math.round(h*ss));out.width=W;out.height=H;const dst=[[0,0],[W-1,0],[W-1,H-1],[0,H-1]],source=p.map(q=>[q[0],q[1]]),M=homography(dst,source),sd=fullCanvas.getContext('2d').getImageData(0,0,img.width,img.height),od=new ImageData(W,H);for(let y=0;y<H;y++)for(let x=0;x<W;x++){let d=M[6]*x+M[7]*y+M[8],sx=(M[0]*x+M[1]*y+M[2])/d,sy=(M[3]*x+M[4]*y+M[5])/d,ix=Math.max(0,Math.min(img.width-1,Math.round(sx))),iy=Math.max(0,Math.min(img.height-1,Math.round(sy))),si=(iy*img.width+ix)*4,oi=(y*W+x)*4;let r=sd.data[si],g=sd.data[si+1],b=sd.data[si+2];if(mode==='clean'){r=Math.min(255,(r-25)*1.18+25);g=Math.min(255,(g-25)*1.18+25);b=Math.min(255,(b-25)*1.18+25)}else if(mode==='bw'){let v=.299*r+.587*g+.114*b;v=v>165?255:v<90?0:(v-90)/75*255;r=g=b=v}od.data[oi]=r;od.data[oi+1]=g;od.data[oi+2]=b;od.data[oi+3]=255}out.getContext('2d').putImageData(od,0,0);$('status').textContent=`Output ${W} × ${H} px`}
function update(){handles();render()}
document.querySelectorAll('.corner').forEach(h=>{h.addEventListener('pointerdown',e=>{e.preventDefault();drag=+h.dataset.i;h.setPointerCapture?.(e.pointerId)});h.addEventListener('pointermove',e=>{if(drag!==+h.dataset.i)return;e.preventDefault();const r=src.getBoundingClientRect();pts[drag]=[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];handles()});h.addEventListener('pointerup',()=>{drag=-1;render()});h.addEventListener('pointercancel',()=>{drag=-1;render()})});
addEventListener('resize',()=>{if(img)requestAnimationFrame(handles)});document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));render()});$('reset').onclick=()=>{reset();update()};$('jpg').onclick=()=>out.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='flat-document.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/jpeg',.94);$('pdf').onclick=async()=>{const blob=await new Promise(r=>out.toBlob(r,'image/jpeg',.94)),jpg=await blob.arrayBuffer(),doc=await PDFLib.PDFDocument.create(),im=await doc.embedJpg(jpg),page=doc.addPage([im.width,im.height]);page.drawImage(im,{x:0,y:0,width:im.width,height:im.height});const data=await doc.save(),url=URL.createObjectURL(new Blob([data],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download='flat-document.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};