const PRIVACY_TAGLINE='Your files never leave your machine.';
(()=>{const p=document.querySelector('.privacy');if(p&&!p.textContent.includes(PRIVACY_TAGLINE))p.innerHTML=`🔒 <strong>${PRIVACY_TAGLINE}</strong> Resizing, cropping and compression happen locally in this browser. No image-processing server is used.`;const f=document.querySelector('footer .wrap');if(f)f.textContent=`© 2026 Clean Local Tools · ${PRIVACY_TAGLINE}`;const d=document.querySelector('meta[name="description"]');if(d&&!d.content.includes(PRIVACY_TAGLINE))d.content=`${PRIVACY_TAGLINE} Resize and compress images locally in your browser. Set dimensions, aspect ratio, format and a target file size.`;const og=document.querySelector('meta[property="og:description"]');if(og&&!og.content.includes(PRIVACY_TAGLINE))og.content=`${PRIVACY_TAGLINE} Make an image meet exact dimensions, aspect ratio, format and file-size requirements locally in your browser.`;document.querySelectorAll('script[type="application/ld+json"]').forEach(s=>{if(!s.textContent.includes(PRIVACY_TAGLINE))try{const j=JSON.parse(s.textContent);j.description=`${PRIVACY_TAGLINE} ${j.description||''}`.trim();s.textContent=JSON.stringify(j)}catch{}})})();
const $=id=>document.getElementById(id);
let source=null,file=null,sourceUrl=null,resultUrl=null,originalRatio=1,crop={x:0,y:0,w:1,h:1},drag=null,imageZoom=1,pinch=null;
const pointers=new Map();
const imageFile=$('imageFile'),chooseImageBtn=$('chooseImageBtn'),editor=$('editor'),preview=$('preview'),width=$('width'),height=$('height'),format=$('format'),targetSize=$('targetSize'),targetUnit=$('targetUnit'),error=$('error'),result=$('result'),cropStage=$('cropStage'),cropOverlay=$('cropOverlay'),cropPanel=$('cropPanel'),cropInfo=$('cropInfo'),outputSummary=$('outputSummary'),previewTitle=$('previewTitle'),previewSubtitle=$('previewSubtitle'),previewHelpText=$('previewHelpText'),resetCropBtn=$('resetCrop'),cropAdjustments=$('cropAdjustments'),imageZoomRange=$('imageZoomRange'),imageZoomValue=$('imageZoomValue'),imageZoomIn=$('imageZoomIn'),imageZoomOut=$('imageZoomOut');
$('cropSizeControls')?.remove();cropOverlay?.querySelectorAll('.handle').forEach(h=>h.remove());
if(imageZoomRange){imageZoomRange.min='50';imageZoomRange.max='300';imageZoomRange.step='5'}
function bytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(2)} MB`}
function showError(m){error.textContent=m;error.hidden=false}function clearError(){error.hidden=true;error.textContent=''}
function selectedFit(){return document.querySelector('input[name="fit"]:checked').value}function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function outRatio(){const w=Number(width.value),h=Number(height.value);return w>0&&h>0?w/h:originalRatio}
function drawContainPreview(){const ratio=outRatio(),max=700;let pw,ph;if(ratio>=1){pw=max;ph=max/ratio}else{ph=max;pw=max*ratio}preview.width=Math.max(1,Math.round(pw));preview.height=Math.max(1,Math.round(ph));const c=preview.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,preview.width,preview.height);const s=Math.min(preview.width/source.naturalWidth,preview.height/source.naturalHeight),dw=source.naturalWidth*s,dh=source.naturalHeight*s;c.drawImage(source,(preview.width-dw)/2,(preview.height-dh)/2,dw,dh)}
function drawPreviewBase(){if(!source)return;if(selectedFit()==='contain')drawContainPreview();else{const max=700,s=Math.min(1,max/source.naturalWidth,max/source.naturalHeight);preview.width=Math.max(1,Math.round(source.naturalWidth*s));preview.height=Math.max(1,Math.round(source.naturalHeight*s));preview.getContext('2d').drawImage(source,0,0,preview.width,preview.height)}requestAnimationFrame(updateOverlay)}
function computeCrop(){if(!source)return;const r=outRatio(),sw=source.naturalWidth,sh=source.naturalHeight;if(sw/sh>r){const h=sh,w=h*r;crop={x:(sw-w)/2,y:0,w,h}}else{const w=sw,h=w/r;crop={x:0,y:(sh-h)/2,w,h}}}
function applyImageZoom(v){if(!source||selectedFit()!=='crop')return;const p=clamp(Number(v)||100,50,300);imageZoom=p/100;imageZoomRange.value=String(p);imageZoomValue.textContent=`${p}%`;updateOverlay()}
function resetCrop(){if(!source)return;computeCrop();imageZoom=1;imageZoomRange.value='100';imageZoomValue.textContent='100%';updateOverlay()}
function zoomViewRect(){const cx=crop.x+crop.w/2,cy=crop.y+crop.h/2,w=crop.w/imageZoom,h=crop.h/imageZoom;return{x:cx-w/2,y:cy-h/2,w,h}}
function updateOverlay(){if(!source)return;const cropMode=selectedFit()==='crop';cropOverlay.hidden=!cropMode;resetCropBtn.hidden=!cropMode;cropAdjustments.hidden=!cropMode;if(cropMode){const sx=preview.clientWidth/source.naturalWidth,sy=preview.clientHeight/source.naturalHeight,cx=(crop.x+crop.w/2)*sx,cy=(crop.y+crop.h/2)*sy;cropOverlay.style.left=`${crop.x*sx}px`;cropOverlay.style.top=`${crop.y*sy}px`;cropOverlay.style.width=`${crop.w*sx}px`;cropOverlay.style.height=`${crop.h*sy}px`;cropOverlay.style.setProperty('--crop-third',`${crop.w*sx/3}px`);preview.style.transformOrigin=`${cx}px ${cy}px`;preview.style.transform=`scale(${imageZoom})`;const v=zoomViewRect();cropInfo.textContent=`View ${Math.round(v.w)} × ${Math.round(v.h)} px · image ${Math.round(imageZoom*100)}%`;previewTitle.textContent='Crop area';previewSubtitle.textContent='The frame is fixed by your requested aspect ratio. Drag it to choose the area, then zoom the image in or out.';previewHelpText.textContent='💡 Drag the crop frame to position it. Pinch with two fingers to zoom the image in or out.'}else{preview.style.transform='none';const w=Math.round(Number(width.value)||0),h=Math.round(Number(height.value)||0);cropInfo.textContent=`Preview ${w} × ${h} px · full image contained`;previewTitle.textContent='Final canvas preview';previewSubtitle.textContent='This preview matches the requested aspect ratio and shows the padding that will appear in the downloaded image.';previewHelpText.textContent='💡 The entire image is kept. White space is shown exactly where the final canvas needs it.'}updateSummary()}
function updateSummary(){const w=Math.round(Number(width.value)||0),h=Math.round(Number(height.value)||0),ext=format.value==='image/jpeg'?'JPG':format.value==='image/webp'?'WebP':'PNG',target=targetSize.value?`${targetSize.value} ${Number(targetUnit.value)===1024?'KB':'MB'}`:'no size limit';outputSummary.innerHTML=w&&h?`Final image: <strong>${w} × ${h} px</strong> · ${ext} · ${target}`:''}
function refreshPreviewForMode(){drawPreviewBase();if(selectedFit()==='crop')resetCrop();else updateOverlay();updateSummary()}
function setRatio(name){document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b.dataset.ratio===name));if(name!=='custom'){const r=name==='original'?originalRatio:Number(name);if(width.value)height.value=Math.max(1,Math.round(Number(width.value)/r))}if(source){computeCrop();if(selectedFit()==='contain')drawPreviewBase();else resetCrop()}updateSummary()}
document.querySelectorAll('.preset').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();setRatio(b.dataset.ratio)}));
width.addEventListener('input',()=>{const a=document.querySelector('.preset.active');if(a&&a.dataset.ratio!=='custom'){const r=a.dataset.ratio==='original'?originalRatio:Number(a.dataset.ratio);height.value=Math.max(1,Math.round(Number(width.value)/r))}if(source){computeCrop();selectedFit()==='contain'?drawPreviewBase():resetCrop()}updateSummary()});
height.addEventListener('input',()=>{document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b.dataset.ratio==='custom'));if(source){computeCrop();selectedFit()==='contain'?drawPreviewBase():resetCrop()}updateSummary()});
[format,targetSize,targetUnit].forEach(el=>el.addEventListener('input',updateSummary));document.querySelectorAll('input[name="fit"]').forEach(r=>r.addEventListener('change',refreshPreviewForMode));
resetCropBtn.addEventListener('click',resetCrop);imageZoomRange.addEventListener('input',()=>applyImageZoom(imageZoomRange.value));imageZoomIn.addEventListener('click',()=>applyImageZoom(Number(imageZoomRange.value)+10));imageZoomOut.addEventListener('click',()=>applyImageZoom(Number(imageZoomRange.value)-10));if(chooseImageBtn)chooseImageBtn.addEventListener('click',()=>{imageFile.value='';imageFile.click()});
function pointerToImage(e){const rect=cropStage.getBoundingClientRect();return{x:(e.clientX-rect.left)*source.naturalWidth/preview.clientWidth,y:(e.clientY-rect.top)*source.naturalHeight/preview.clientHeight}}
function startDrag(e){if(!source||selectedFit()!=='crop'||pinch)return;e.preventDefault();drag={start:pointerToImage(e),orig:{...crop}};cropOverlay.setPointerCapture?.(e.pointerId)}
cropOverlay.addEventListener('pointerdown',startDrag);cropOverlay.addEventListener('pointermove',e=>{if(!drag||!source||pinch)return;e.preventDefault();const p=pointerToImage(e),dx=p.x-drag.start.x,dy=p.y-drag.start.y;crop.x=clamp(drag.orig.x+dx,0,source.naturalWidth-drag.orig.w);crop.y=clamp(drag.orig.y+dy,0,source.naturalHeight-drag.orig.h);crop.w=drag.orig.w;crop.h=drag.orig.h;updateOverlay()});
function endDrag(e){if(!drag)return;drag=null;try{cropOverlay.releasePointerCapture?.(e.pointerId)}catch{}}cropOverlay.addEventListener('pointerup',endDrag);cropOverlay.addEventListener('pointercancel',endDrag);
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}cropStage.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||selectedFit()!=='crop')return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){drag=null;const pts=[...pointers.values()];pinch={distance:distance(pts[0],pts[1]),zoom:imageZoom};try{cropStage.setPointerCapture(e.pointerId)}catch{}}});cropStage.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&pointers.size>=2){e.preventDefault();const pts=[...pointers.values()].slice(0,2),d=distance(pts[0],pts[1]);if(pinch.distance>0)applyImageZoom(pinch.zoom*(d/pinch.distance)*100)}});function finishPointer(e){pointers.delete(e.pointerId);if(pointers.size<2)pinch=null}cropStage.addEventListener('pointerup',finishPointer);cropStage.addEventListener('pointercancel',finishPointer);window.addEventListener('resize',updateOverlay);
function renderCropOutput(c,outW,outH){const v=zoomViewRect(),sx1=Math.max(0,v.x),sy1=Math.max(0,v.y),sx2=Math.min(source.naturalWidth,v.x+v.w),sy2=Math.min(source.naturalHeight,v.y+v.h);if(sx2<=sx1||sy2<=sy1)return;const sw=sx2-sx1,sh=sy2-sy1,dx=(sx1-v.x)/v.w*outW,dy=(sy1-v.y)/v.h*outH,dw=sw/v.w*outW,dh=sh/v.h*outH;c.drawImage(source,sx1,sy1,sw,sh,dx,dy,dw,dh)}
function renderOutput(canvas,w,h){canvas.width=w;canvas.height=h;const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,w,h);if(selectedFit()==='crop')renderCropOutput(c,w,h);else{const s=Math.min(w/source.naturalWidth,h/source.naturalHeight),dw=source.naturalWidth*s,dh=source.naturalHeight*s;c.drawImage(source,(w-dw)/2,(h-dh)/2,dw,dh)}}
function canvasBlob(canvas,type,q){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('This browser could not create the requested image.')),type,q))}
async function encode(canvas,type,target){if(type==='image/png'){const blob=await canvasBlob(canvas,type);return{blob,quality:null,reached:!target||blob.size<=target}}if(!target){const blob=await canvasBlob(canvas,type,.92);return{blob,quality:.92,reached:true}}let lo=.05,hi=.98,best=null;for(let i=0;i<10;i++){const q=(lo+hi)/2,blob=await canvasBlob(canvas,type,q);if(blob.size<=target){best={blob,quality:q};lo=q}else hi=q}if(best)return{...best,reached:true};const blob=await canvasBlob(canvas,type,.05);return{blob,quality:.05,reached:blob.size<=target}}
imageFile.addEventListener('change',()=>{clearError();file=imageFile.files[0];if(!file)return;const looksLikeImage=(file.type||'').startsWith('image/')||/\.(jpe?g|png|webp|heic|heif)$/i.test(file.name||'');if(!looksLikeImage){showError('Please choose an image file.');return}if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(file);source=new Image();source.onload=()=>{originalRatio=source.naturalWidth/source.naturalHeight;width.value=source.naturalWidth;height.value=source.naturalHeight;$('originalInfo').textContent=`Original: ${source.naturalWidth} × ${source.naturalHeight} px · ${bytes(file.size)}`;editor.hidden=false;result.hidden=true;cropPanel.hidden=false;setRatio('original');drawPreviewBase();resetCrop();editor.scrollIntoView({behavior:'smooth',block:'start'})};source.onerror=()=>showError('This image format could not be opened by your browser. Try JPG, PNG or WebP.');source.src=sourceUrl});
$('processBtn').addEventListener('click',async()=>{clearError();result.hidden=true;const w=Math.round(Number(width.value)),h=Math.round(Number(height.value));if(!source||!w||!h||w<1||h<1||w>12000||h>12000){showError('Enter valid dimensions between 1 and 12,000 pixels.');return}const target=targetSize.value?Number(targetSize.value)*Number(targetUnit.value):null;if(targetSize.value&&(!target||target<=0)){showError('Enter a valid maximum file size.');return}const btn=$('processBtn');btn.disabled=true;btn.textContent='Processing…';try{const canvas=document.createElement('canvas');renderOutput(canvas,w,h);const encoded=await encode(canvas,format.value,target);if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(encoded.blob);const ext=format.value==='image/jpeg'?'jpg':format.value==='image/webp'?'webp':'png',base=file.name.replace(/\.[^.]+$/,'')||'image';$('downloadBtn').href=resultUrl;$('downloadBtn').download=`${base}-${w}x${h}.${ext}`;const saved=file.size-encoded.blob.size,savings=file.size>0?Math.round(saved/file.size*100):0;const checks=[`✓ ${w} × ${h} px`,`✓ ${ext.toUpperCase()}`,`Original size: ${bytes(file.size)}`,`Final file size: ${bytes(encoded.blob.size)}`];if(saved>0)checks.push(`✓ ${savings}% smaller`);else if(saved<0)checks.push(`⚠ ${Math.abs(savings)}% larger`);if(target)checks.push(encoded.reached?`✓ Under ${bytes(target)}`:`⚠ Target ${bytes(target)} not reached`);$('checks').innerHTML=checks.map(t=>`<span class="check">${t}</span>`).join('');let meta=`Original size ${bytes(file.size)} → Final file size ${bytes(encoded.blob.size)}`;if(selectedFit()==='crop'){const v=zoomViewRect();meta+=` · View ${Math.round(v.w)} × ${Math.round(v.h)} px · Image zoom ${imageZoomRange.value}%`}else meta+=' · Entire image contained';if(encoded.quality!==null)meta+=` · Quality ${Math.round(encoded.quality*100)}%`;if(format.value==='image/png'&&target&&encoded.blob.size>target)meta+=' · PNG is lossless, so quality cannot be lowered to force a smaller file.';$('resultMeta').textContent=meta;result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'center'})}catch(err){showError(err.message||'Could not process this image.')}finally{btn.disabled=false;btn.textContent='Resize & Compress Image'}});