(() => {
  const input=document.getElementById('photoFile'),choose=document.getElementById('chooseBtn'),editor=document.getElementById('editor'),preview=document.getElementById('preview'),metadata=document.getElementById('metadata'),note=document.getElementById('note'),cleanBtn=document.getElementById('cleanBtn'),status=document.getElementById('status'),error=document.getElementById('error'),result=document.getElementById('result'),resultText=document.getElementById('resultText'),download=document.getElementById('download');
  let file=null,img=null,previewUrl=null,downloadUrl=null;
  const important=['latitude','longitude','GPSLatitude','GPSLongitude','Make','Model','DateTimeOriginal','CreateDate','Software','LensModel','Artist','Copyright'];
  function addPair(k,v){const key=document.createElement('div');key.className='key';key.textContent=k;const value=document.createElement('div');value.className='value';value.textContent=String(v);metadata.append(key,value);}
  function decode(f){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(f),el=new Image();el.onload=()=>resolve({el,url});el.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('decode'));};el.src=url;});}
  async function inspect(f){error.textContent='';result.hidden=true;status.textContent='Reading photo…';try{const decoded=await decode(f);if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=decoded.url;img=decoded.el;file=f;preview.src=previewUrl;metadata.innerHTML='';addPair('File',f.name);addPair('Type',f.type||'Unknown');addPair('Dimensions',`${img.naturalWidth} × ${img.naturalHeight}`);let data=null;if(window.exifr&&typeof window.exifr.parse==='function'){try{data=await window.exifr.parse(f,{gps:true,tiff:true,exif:true,icc:false,iptc:true,xmp:true});}catch{data=null;}}let count=0;if(data){const seen=new Set();for(const k of important){if(data[k]!==undefined&&data[k]!==null&&!seen.has(k)){addPair(k,data[k]);seen.add(k);count++;}}for(const [k,v] of Object.entries(data)){if(count>=18)break;if(v===undefined||v===null||typeof v==='object'||seen.has(k))continue;addPair(k,v);seen.add(k);count++;}}note.textContent=count?`${count} embedded metadata field${count===1?'':'s'} shown. The clean copy removes the original metadata block.`:'No readable EXIF fields were found. Creating a clean copy will still rewrite the image pixels.';editor.hidden=false;status.textContent='';}catch{status.textContent='';editor.hidden=true;error.textContent='This photo could not be read. Please choose JPG, PNG or WebP.';}}
  async function clean(){if(!file||!img)return;cleanBtn.disabled=true;error.textContent='';status.textContent='Creating clean copy…';try{const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d');if(file.type==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);}ctx.drawImage(img,0,0);const type=file.type==='image/png'?'image/png':file.type==='image/webp'?'image/webp':'image/jpeg';const blob=await new Promise(resolve=>canvas.toBlob(resolve,type,type==='image/jpeg'?0.94:0.92));if(!blob)throw new Error('encode');if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(blob);const ext=type==='image/png'?'png':type==='image/webp'?'webp':'jpg';const base=file.name.replace(/\.[^.]+$/,'');download.href=downloadUrl;download.download=`${base}-clean.${ext}`;resultText.textContent=`${img.naturalWidth}×${img.naturalHeight} · ${(blob.size/1024).toFixed(1)} KB`;result.hidden=false;status.textContent='';}catch{status.textContent='';error.textContent='The clean copy could not be created.';}finally{cleanBtn.disabled=false;}}
  choose.addEventListener('click',()=>input.click());input.addEventListener('change',e=>{const f=e.target.files&&e.target.files[0];if(f)inspect(f);input.value='';});cleanBtn.addEventListener('click',clean);
})();