import * as pdfjsLib from 'https://cdn.jsdelivr.net/npm/pdfjs-dist@5.7.284/build/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@5.7.284/build/pdf.worker.min.mjs';
const $=id=>document.getElementById(id);let bytes=null,pdf=null,page=1,scale=1,masks={},removed=new Set(),drag=null,cleanUrl=null;
const canvas=$('preview'),stage=$('stage'),status=$('status');
$('pdfFile').addEventListener('change',async()=>{const f=$('pdfFile').files[0];if(!f)return;$('error').textContent='Loading PDF…';try{bytes=new Uint8Array(await f.arrayBuffer());pdf=await pdfjsLib.getDocument({data:bytes.slice()}).promise;page=1;masks={};removed.clear();$('editor').hidden=false;$('error').textContent='';await render()}catch(e){$('error').textContent='Could not open this PDF.'}});
async function render(){const p=await pdf.getPage(page),base=p.getViewport({scale:1}),max=Math.min(760,window.innerWidth-60);scale=Math.min(1.5,max/base.width);const v=p.getViewport({scale});canvas.width=Math.round(v.width);canvas.height=Math.round(v.height);await p.render({canvasContext:canvas.getContext('2d'),viewport:v}).promise;stage.querySelectorAll('.mask').forEach(x=>x.remove());(masks[page]||[]).forEach(drawMask);$('pageInfo').textContent=`Page ${page} of ${pdf.numPages}${removed.has(page)?' · removed':''}`;$('prev').disabled=page===1;$('next').disabled=page===pdf.numPages;$('removePage').textContent=removed.has(page)?'Restore page':'Remove page';$('undo').disabled=!(masks[page]?.length)}
function drawMask(m){const d=document.createElement('div');d.className='mask';d.style.left=`${m.x*canvas.width}px`;d.style.top=`${m.y*canvas.height}px`;d.style.width=`${m.w*canvas.width}px`;d.style.height=`${m.h*canvas.height}px`;stage.appendChild(d)}
function pos(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)*canvas.height/r.height))}}
stage.addEventListener('pointerdown',e=>{if(!pdf||removed.has(page))return;e.preventDefault();stage.setPointerCapture?.(e.pointerId);const p=pos(e),el=document.createElement('div');el.className='mask';stage.appendChild(el);drag={start:p,el}});stage.addEventListener('pointermove',e=>{if(!drag)return;const p=pos(e),x=Math.min(p.x,drag.start.x),y=Math.min(p.y,drag.start.y),w=Math.abs(p.x-drag.start.x),h=Math.abs(p.y-drag.start.y);Object.assign(drag.el.style,{left:`${x}px`,top:`${y}px`,width:`${w}px`,height:`${h}px`})});stage.addEventListener('pointerup',e=>{if(!drag)return;const p=pos(e),x=Math.min(p.x,drag.start.x),y=Math.min(p.y,drag.start.y),w=Math.abs(p.x-drag.start.x),h=Math.abs(p.y-drag.start.y);drag.el.remove();drag=null;if(w>5&&h>5){(masks[page]??=[]).push({x:x/canvas.width,y:y/canvas.height,w:w/canvas.width,h:h/canvas.height});render()}});
$('prev').onclick=()=>{if(page>1){page--;render()}};$('next').onclick=()=>{if(page<pdf.numPages){page++;render()}};$('undo').onclick=()=>{masks[page]?.pop();render()};$('removePage').onclick=()=>{removed.has(page)?removed.delete(page):removed.add(page);render()};
async function makeClean(){if(!bytes)return null;status.textContent='Creating clean PDF…';const src=await PDFLib.PDFDocument.load(bytes.slice()),out=await PDFLib.PDFDocument.create();for(let i=0;i<src.getPageCount();i++){const n=i+1;if(removed.has(n))continue;const [copied]=await out.copyPages(src,[i]);out.addPage(copied);const pg=out.getPage(out.getPageCount()-1),{width:w,height:h}=pg.getSize();for(const m of masks[n]||[])pg.drawRectangle({x:m.x*w,y:h-(m.y+m.h)*h,width:m.w*w,height:m.h*h,color:PDFLib.rgb(1,1,1),borderWidth:0})}if(out.getPageCount()===0)throw new Error('Keep at least one page.');return await out.save()}
async function cleanBlob(){const data=await makeClean();const blob=new Blob([data],{type:'application/pdf'});if(cleanUrl)URL.revokeObjectURL(cleanUrl);cleanUrl=URL.createObjectURL(blob);status.textContent=`Clean PDF ready · ${outCount()} page${outCount()===1?'':'s'}`;return blob}
function outCount(){return pdf?pdf.numPages-removed.size:0}
$('download').onclick=async()=>{try{await cleanBlob();const a=document.createElement('a');a.href=cleanUrl;a.download='clean-print.pdf';a.click()}catch(e){status.textContent=e.message}};$('print').onclick=async()=>{try{await cleanBlob();const win=window.open(cleanUrl,'_blank');if(win)setTimeout(()=>win.print(),700);else status.textContent='Allow pop-ups to open the print dialog.'}catch(e){status.textContent=e.message}};