(() => {
  const input=document.getElementById('pdfFile'),choose=document.getElementById('chooseBtn'),editor=document.getElementById('editor'),pagesEl=document.getElementById('pages'),summary=document.getElementById('summary'),selectAll=document.getElementById('selectAll'),clearAll=document.getElementById('clearAll'),extractBtn=document.getElementById('extractBtn'),splitBtn=document.getElementById('splitBtn'),status=document.getElementById('status'),error=document.getElementById('error'),result=document.getElementById('result'),resultTitle=document.getElementById('resultTitle'),resultText=document.getElementById('resultText'),download=document.getElementById('download');
  let file=null,sourceBytes=null,pageCount=0,selected=new Set(),downloadUrl=null;
  const clearError=()=>error.textContent=''; const showError=m=>error.textContent=m;
  function render(){editor.hidden=!file;pagesEl.innerHTML='';for(let i=0;i<pageCount;i++){const label=document.createElement('label');label.className='page-tile'+(selected.has(i)?' selected':'');const cb=document.createElement('input');cb.type='checkbox';cb.checked=selected.has(i);cb.dataset.page=String(i);cb.addEventListener('change',()=>{cb.checked?selected.add(i):selected.delete(i);render();});const n=document.createElement('div');n.className='page-number';n.textContent=`Page ${i+1}`;label.append(cb,n);pagesEl.append(label);}summary.textContent=`${pageCount} ${pageCount===1?'page':'pages'} · ${selected.size} selected`;extractBtn.disabled=selected.size===0;}
  async function loadFile(f){clearError();result.hidden=true;if(!f)return;if(!window.PDFLib){showError('The PDF library could not be loaded.');return;}try{status.textContent='Reading PDF…';sourceBytes=await f.arrayBuffer();const doc=await PDFLib.PDFDocument.load(sourceBytes,{ignoreEncryption:false});file=f;pageCount=doc.getPageCount();selected=new Set(Array.from({length:pageCount},(_,i)=>i));render();status.textContent='';}catch(e){file=null;editor.hidden=true;status.textContent='';showError(/encrypt|password/i.test(String(e?.message||e))?'Password-protected PDFs are not supported yet.':'The PDF could not be read.');}finally{input.value='';}}
  function setDownload(blob,name,title,text){if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(blob);download.href=downloadUrl;download.download=name;resultTitle.textContent=title;resultText.textContent=text;result.hidden=false;}
  async function extract(){if(!file||!selected.size)return;clearError();extractBtn.disabled=true;splitBtn.disabled=true;try{status.textContent='Extracting selected pages…';const src=await PDFLib.PDFDocument.load(sourceBytes);const out=await PDFLib.PDFDocument.create();const indices=[...selected].sort((a,b)=>a-b);const copied=await out.copyPages(src,indices);copied.forEach(p=>out.addPage(p));const bytes=await out.save({useObjectStreams:true});setDownload(new Blob([bytes],{type:'application/pdf'}),'extracted-pages.pdf','Extracted PDF is ready',`${indices.length} ${indices.length===1?'page':'pages'} selected`);status.textContent='';}catch{status.textContent='';showError('The selected pages could not be extracted.');}finally{render();splitBtn.disabled=false;}}
  async function split(){if(!file)return;if(!window.JSZip){showError('The ZIP library could not be loaded.');return;}extractBtn.disabled=true;splitBtn.disabled=true;clearError();try{const src=await PDFLib.PDFDocument.load(sourceBytes);const zip=new JSZip();for(let i=0;i<pageCount;i++){status.textContent=`Creating page ${i+1} of ${pageCount}…`;const out=await PDFLib.PDFDocument.create();const [p]=await out.copyPages(src,[i]);out.addPage(p);zip.file(`page-${i+1}.pdf`,await out.save({useObjectStreams:true}));}status.textContent='Creating ZIP…';const blob=await zip.generateAsync({type:'blob'});setDownload(blob,'split-pages.zip','Split PDF is ready',`${pageCount} individual PDF ${pageCount===1?'file':'files'} in one ZIP`);status.textContent='';}catch{status.textContent='';showError('The PDF could not be split.');}finally{splitBtn.disabled=false;render();}}
  choose.addEventListener('click',()=>input.click());input.addEventListener('change',e=>loadFile(e.target.files[0]));selectAll.addEventListener('click',()=>{selected=new Set(Array.from({length:pageCount},(_,i)=>i));render();});clearAll.addEventListener('click',()=>{selected.clear();render();});extractBtn.addEventListener('click',extract);splitBtn.addEventListener('click',split);
})();